### ISSUE TITLE
Dimension scaling is not working

### ISSUE THREAD

**Issue by Whitebrim** [Lauriethefish/BetterPortals#131]
I use multiverse nether portals with 1:1 nether cordinates. 
I changed config to this ↓ but nether portals keep creating in 1:8 cordinates.

```
worldConnections:
  '0':
    originWorld: 'world'
    destinationWorld: 'world_nether'
    minSpawnY: 5
    maxSpawnY: 122
    coordinateRescalingFactor: 1.0
  '1':
    originWorld: 'world_nether'
    destinationWorld: 'world'
    minSpawnY: 5
    maxSpawnY: 250
    coordinateRescalingFactor: 1.0
```

Plugin Version: 0.10.2
Game Version: Pufferfish v40 (1.18.1)
